### ISSUE TITLE
Add code example for -  S: Single Responsibility Principle

### ISSUE THREAD

**Issue by muhammadawaisshaikh** [thrashtechinfo/solid-design-pattern-angular#1]
- Before Applying: Consider a component that displays a list of courses and allows the student to filter them by degree-program.

- After Applying:
  1. create a new component that displays the list of courses
  2. Now, we will create a new component that handles the degree-program filtering

**Comment by thrashtechinfo** [comment]
@muhammadawaisshaikh  let's add this in terms of component level with and without - S: Single Responsibility Principle
