### ISSUE TITLE
Add code example for - O: Open/Closed Principle

### ISSUE THREAD

**Issue by muhammadawaisshaikh** [thrashtechinfo/solid-design-pattern-angular#2]
- Before Applying: We have a component that displays a list of courses. The courses are retrieved and displayed in a table. The table has three columns: course name, instructor, and duration. We have created a CourseListComponent to display this list
- After Applying:
  1. UserListComponent: This component will be responsible for displaying the list of users. It will show basic information such as the name, email, and phone number in a table format. When a user is selected, their details will be displayed by the new component.
  2. UserDetailComponent: This new component will handle displaying additional details for the selected user. It will take the selected user as an input and show more specific information (such as address, age, or other relevant data).

**Comment by thrashtechinfo** [comment]
@muhammadawaisshaikh let's add this in terms of component level with and without - O: Open/Closed Principle

**Comment by thrashtechinfo** [comment]
done, thanks
