### ISSUE TITLE
Add code example for - L: Liskov Substitution Principle

### ISSUE THREAD

**Issue by muhammadawaisshaikh** [thrashtechinfo/solid-design-pattern-angular#3]
1. With LSP: Subclasses like CreditCardPaymentService and PaypalPaymentService properly replace the PaymentService class without breaking the logic of the PaymentComponent. The system is easy to extend and maintain.
  2. Without LSP: Introducing a subclass like CryptoPaymentService that doesn’t properly adhere to the expected behavior of the base class results in runtime errors and requires additional error handling, making the code less maintainable and extensible.

**Comment by thrashtechinfo** [comment]
@muhammadawaisshaikh let's add this in terms of component level with and without - L: Liskov Substitution Principle

**Comment by thrashtechinfo** [comment]
done, thanks
