### ISSUE TITLE
Add code example for - I: Interface Segregation Principle

### ISSUE THREAD

**Issue by muhammadawaisshaikh** [thrashtechinfo/solid-design-pattern-angular#4]
1. Without: Imagine you're building an e-commerce application and have an interface for different types of payments. If you have a PaymentProcessor interface with a bunch of methods, but not all payment methods require all those methods, you violate the ISP.
  2. With: you should split the PaymentProcessor interface into smaller, more specific interfaces. This way, each class only implements the methods it actually needs.

**Comment by thrashtechinfo** [comment]
@muhammadawaisshaikh let's add this in terms of component level with and without - I: Interface Segregation Principle

**Comment by thrashtechinfo** [comment]
done, thanks
